import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThumbnailContextProvider from "@/context/thumbnail-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark relative min-h-screen`}>
        <div className="fixed z-50 top-0 w-full h-16 bg-gradient-to-b from-background to-transparent pointer-events-none "></div>
        <ThumbnailContextProvider>
        {children}
        </ThumbnailContextProvider>
      </body>
    </html>
  );
}
